### ISSUE TITLE
Gunicron FastAPI - Value Error while importing sketch

### ISSUE THREAD

**Issue by adianavin** [approximatelabs/sketch#27]
Getting below error while importing sketch library

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/api/main.py", line 15, in <module>
    import chat
  File "/home/ubuntu/api/chat.py", line 25, in <module>
    import sketch
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sketch/__init__.py", line 2, in <module>
    from .pandas_extension import SketchHelper  # noqa
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sketch/pandas_extension.py", line 16, in <module>
    import lambdaprompt
  File "/home/ubuntu/.local/lib/python3.10/site-packages/lambdaprompt/__init__.py", line 8, in <module>
    nest_asyncio.apply()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nest_asyncio.py", line 14, in apply
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
[2023-06-29 06:34:51 +0000] [341645] [INFO] Worker exiting (pid: 341645)
[2023-06-29 06:34:51 +0000] [341644] [INFO] Shutting down: Master
[2023-06-29 06:34:51 +0000] [341644] [INFO] Reason: Worker failed to boot.

Code:
`import sketch
content = df.sketch.ask("hello", call_display=False)`

**Comment by bluecoconut** [comment]
https://github.com/approximatelabs/lambdaprompt/issues/4

From `lambdaprompt`, fix is to change the active loop

**Comment by adianavin** [comment]
Hello,
All threads i can see is belongs to uvicorn. I am getting an error in gunicorn.
`import asyncio
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
import sketch
content = df.sketch.ask("hello", call_display=False)
`
I tried this

` import asyncio
 from contextlib import contextmanager

 @contextmanager
 def setup_event_loop():
     loop = asyncio.new_event_loop()
     asyncio.set_event_loop(loop)
     try:
         yield loop
     finally:
         loop.close()
         asyncio.set_event_loop(None)


 with setup_event_loop() as loop:
     import sketch`

**Comment by adianavin** [comment]
gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001 --forwarded-allow-ips '*'

**Comment by adianavin** [comment]
Please somebody help

**Comment by bluecoconut** [comment]
Add `--loop asyncio` to your `gunicorn` command

https://github.com/approximatelabs/lambdaprompt/issues/4#issuecomment-1397946118

**Comment by adianavin** [comment]
getting below error
`usage: gunicorn [OPTIONS] [APP_MODULE] 
gunicorn: error: unrecognized arguments: --loop asyncio`

**Comment by bluecoconut** [comment]
Ah, oops, can you use `uvicorn` instead of `gunicorn`? 

`gunicorn` doesn't have async support, so to get that you'll want an async handler.
